# -*- coding: utf-8 -*-
"""Calculadora Hexadecimal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4MKixCIuODCJoIV-O3CxPHjONcQij2G
"""

opcao1 = '1'
opcao2 = '2'
opcao3 = '3'

# CONVERTE O VALOR DECIMAL EM HEXADECIMAL E BINÁRIO
def decimal_para_demais(a):
  a = int(a)
  dec_hex = hex(a)[2:]
  dec_nib = bin(a)[2:]
  lista_dec_nibble = []

  # CASO O PRIMEIRO OCTETO ESTEJA INCOMPLETO, ELE IRÁ ADICIONAR "0" NO INÍCIO DELE, ATÉ COMPLETÁ-LO
  while((len(dec_nib) % 4) != 0):
    dec_nib = '0' + str(dec_nib)

  # DO ÚLTIMO PARA O PRIMEIRO, ELE IRÁ SEPARAR CADA OCTETO COM UM PONTO
  # CADA "1", "0" E PONTO SÃO UM ITEM DA LISTA
  for octetos in range(len(dec_nib), 0, -1):
    if(octetos == len(dec_nib)):
      lista_dec_nibble.append(dec_nib[octetos-1])
    elif((octetos % 4) == 0):
      lista_dec_nibble.append('.')
      lista_dec_nibble.append(dec_nib[octetos-1])
    else:
      lista_dec_nibble.append(dec_nib[octetos-1])

  # UNE OS ITENS DA LISTA EM UM SÓ E INVERTE A ORDEM
  dec_nib = ''.join(reversed(lista_dec_nibble))

  return dec_hex.upper(), dec_nib

# CONVERTE O VALOR BINÁRIO PARA DECIMAL E HEXADECIMAL
def nibble_para_demais(b):

  nib_dec = int(b, 2)
  nib_hex = hex(nib_dec)[2:]

  return nib_dec, nib_hex.upper()

# CONVERTE O VALOR HEXADECIMAL PARA DECIMAL E BINÁRIO
def hexadecimal_para_demais(c):
  hex_dec = int(c, 16)
  hex_nib = bin(hex_dec)[2:]
  lista_hex_nibble = []

  # CASO O PRIMEIRO OCTETO ESTEJA INCOMPLETO, ELE IRÁ ADICIONAR "0" NO INÍCIO DELE, ATÉ COMPLETÁ-LO
  while((len(hex_nib) % 4) != 0):
    hex_nib = '0' + str(hex_nib)

  # DO ÚLTIMO PARA O PRIMEIRO, ELE IRÁ SEPARAR CADA OCTETO COM UM PONTO
  # CADA "1", "0" E PONTO SÃO UM ITEM DA LISTA
  for octetos in range(len(hex_nib), 0, -1):
    if(octetos == len(hex_nib)):
      lista_hex_nibble.append(hex_nib[octetos-1])
    elif((octetos % 4) == 0):
      lista_hex_nibble.append('.')
      lista_hex_nibble.append(hex_nib[octetos-1])
    else:
      lista_hex_nibble.append(hex_nib[octetos-1])

  # UNE OS ITENS DA LISTA EM UM SÓ E INVERTE A ORDEM
  hex_nib = ''.join(reversed(lista_hex_nibble))

  return hex_dec, hex_nib

# VERIFICA SE NO HEXADECIMAL DIGITADO, HÁ SOMENTE NÚMEROS E LETRAS DE "A" Á "F", TODAS MAIÚSCULAS
def verificar_hexadecimal(d):
  range_ord_min_num = 48
  range_ord_max_num = 57
  range_ord_min_letras = 65
  range_ord_max_letras = 70
  somente_hex = None

  for digitos_hex in d:
    if((ord(digitos_hex) in range(range_ord_min_num, range_ord_max_num + 1)) or (ord(digitos_hex) in range(range_ord_min_letras, range_ord_max_letras + 1))):
      somente_hex = True
    else:
      somente_hex = False
      break

  return somente_hex

# VERIFICA SE NO BINÁRIA DIGITADO, HÁ SOMENTE OS NÚMEROS "0" E "1"
def verificar_nibble(e):
  somente_bin = True

  for digitos_nib in e:
    if((digitos_nib != '0') and (digitos_nib != '1')):
      somente_bin = False
      break

  return somente_bin

# VERIFICA SE NO DECIMAL DIGITADO, HÁ SOMENTE NÚMEROS
def verificar_decimal(f):
  somente_num = True
  try:
    f = int(f)
  except ValueError:
    somente_num = False

  return somente_num

if __name__ == '__main__':
  print('Bem-vindo usuário!')
  print('Este programa é uma calculadora de programador.')

  while(True):
    print('Estas são as seguintes opções de cálculos:')
    print('1 - Decimal -> Hexadecimal e Binário\n2 - Binário -> Decimal e Hexadecimal\n3 - Hexadecimal -> Decimal e Binário')
    print('Por favor, escolha uma dessas opções:')
    escolha_user = input()
    print('-' * 30)

    if((escolha_user == opcao1) or (escolha_user == opcao2) or (escolha_user == opcao3)):
      while(True):
        print('Agora, digite no seguinte formato:')
        if(escolha_user == opcao1):
          print('Somente números!')
        elif(escolha_user == opcao2):
          print('Somente números 1 e 0, sem pontos!')
        else:
          print('Somente números e as letras de A à F, todas MAÍUSCULAS!')

        texto_user = input()
        print('-' * 30)

        if(escolha_user == opcao1):
          condicao_decimal = verificar_decimal(texto_user)
          if(condicao_decimal == True):
            resultado1, resultado2 = decimal_para_demais(texto_user)
            print(f'Decimal -> Hexadecimal = {resultado1}')
            print(f'Decimal -> Binário = {resultado2}')
            break
          else:
            print('Erro! Você não digitou somente números!')
        elif(escolha_user == opcao2):
          condicao_nibble = verificar_nibble(texto_user)
          if(condicao_nibble == True):
            resultado1, resultado2 = nibble_para_demais(texto_user)
            print(f'Binário -> Decimal = {resultado1}')
            print(f'Binário -> Hexadecimal = {resultado2}')
            break
          else:
            print('Erro! Você não digitou somente os números 0 e 1!')
        else:
          condicao_hexadecimal = verificar_hexadecimal(texto_user)
          if(condicao_hexadecimal == True):
            resultado1, resultado2 = hexadecimal_para_demais(texto_user)
            print(f'Hexadecimal -> Decimal = {resultado1}')
            print(f'Hexadecimal -> Binário = {resultado2}')
            break
          else:
            print('Erro! Você não digitou somente os números e letras disponíveis!')
        print('Por favor, tente novamente!')
        print('-' * 30)
      break
    else:
      print('Erro! Você não digitou uma das opções disponíveis!')
      print('Por favor, tente novamente!')
      print('-' * 30)