# -*- coding: utf-8 -*-
"""Programmer Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjJkPaSJfBloXTzveBepZkn3sj0EzdbV
"""

opcao1 = '1'
opcao2 = '2'
opcao3 = '3'

# CONVERTS THE DECIMAL VALUE TO HEXADECIMAL DN BINARY
def decimal_para_demais(a):
  a = int(a)
  dec_hex = hex(a)[2:]
  dec_nib = bin(a)[2:]
  lista_dec_nibble = []

  # iF THE FIRST oCTET IS INCOMPLETE, IT WILL ADD "0" ON THE START OF IT, UNTIL IT'S COMPLETED
  while((len(dec_nib) % 4) != 0):
    dec_nib = '0' + str(dec_nib)

  # FORM DE LAST TO THE FIRST, IT WILL SPLIT EACH OCTET WITH A DOT
  # EACH "1", "0" AND DOT ARE A ITEM ON THE LIST
  for octetos in range(len(dec_nib), 0, -1):
    if(octetos == len(dec_nib)):
      lista_dec_nibble.append(dec_nib[octetos-1])
    elif((octetos % 4) == 0):
      lista_dec_nibble.append('.')
      lista_dec_nibble.append(dec_nib[octetos-1])
    else:
      lista_dec_nibble.append(dec_nib[octetos-1])

  # GATHER THE ITENS OF THE LIST IN ONE ITEN AND REVERSE THE ORDER
  dec_nib = ''.join(reversed(lista_dec_nibble))

  return dec_hex.upper(), dec_nib

# CONVERT THE BINARY VALUE TO DECIMAL AND HEXADECIMAL
def nibble_para_demais(b):

  nib_dec = int(b, 2)
  nib_hex = hex(nib_dec)[2:]

  return nib_dec, nib_hex.upper()

# CONVERT THE HEXADECIMAL VALUE TO DECIMAL AND BINARY
def hexadecimal_para_demais(c):
  hex_dec = int(c, 16)
  hex_nib = bin(hex_dec)[2:]
  lista_hex_nibble = []

  # iF THE FIRST oCTET IS INCOMPLETE, IT WILL ADD "0" ON THE START OF IT, UNTIL IT'S COMPLETED
  while((len(hex_nib) % 4) != 0):
    hex_nib = '0' + str(hex_nib)

  # FORM DE LAST TO THE FIRST, IT WILL SPLIT EACH OCTET WITH A DOT
  # EACH "1", "0" AND DOT ARE A ITEM ON THE LIST
  for octetos in range(len(hex_nib), 0, -1):
    if(octetos == len(hex_nib)):
      lista_hex_nibble.append(hex_nib[octetos-1])
    elif((octetos % 4) == 0):
      lista_hex_nibble.append('.')
      lista_hex_nibble.append(hex_nib[octetos-1])
    else:
      lista_hex_nibble.append(hex_nib[octetos-1])

  # GATHER THE ITENS OF THE LIST IN ONE ITEN AND REVERSE THE ORDER
  hex_nib = ''.join(reversed(lista_hex_nibble))

  return hex_dec, hex_nib

# CHECK IF THE TYPED HEXADECIMAL, THERE IS JUST NUMBERS AND THE LETTERS "A" TO "F", ALL IN CAPITAL LETTERS
def verificar_hexadecimal(d):
  range_ord_min_num = 48
  range_ord_max_num = 57
  range_ord_min_letras = 65
  range_ord_max_letras = 70
  somente_hex = None

  for digitos_hex in d:
    if((ord(digitos_hex) in range(range_ord_min_num, range_ord_max_num + 1)) or (ord(digitos_hex) in range(range_ord_min_letras, range_ord_max_letras + 1))):
      somente_hex = True
    else:
      somente_hex = False
      break

  return somente_hex

# CHECK IF THE TYPED BINARY, THERE IS JUST THE NUMBERS "0" AND "1"
def verificar_nibble(e):
  somente_bin = True

  for digitos_nib in e:
    if((digitos_nib != '0') and (digitos_nib != '1')):
      somente_bin = False
      break

  return somente_bin

# VERIFIES IF THE TYPED DECIMAL, THERE IS JUST NUMBERS
def verificar_decimal(f):
  somente_num = True
  try:
    f = int(f)
  except ValueError:
    somente_num = False

  return somente_num

if __name__ == '__main__':
  print('Welcome user!')
  print('This program is a programmer calculator.')

  while(True):
    print('These are the following calculation options:')
    print('1 - Decimal -> Hexadecimal and Binary\n2 - Binary -> Decimal and Hexadecimal\n3 - Hexadecimal -> Decimal and Binary')
    print('Please, choose one of theses options:')
    escolha_user = input()
    print('-' * 30)

    if((escolha_user == opcao1) or (escolha_user == opcao2) or (escolha_user == opcao3)):
      while(True):
        print('Now, type in the following format:')
        if(escolha_user == opcao1):
          print('Just numbers!')
        elif(escolha_user == opcao2):
          print('Just the numbers 1 and 0, no dots!')
        else:
          print('Just numbers and the letters A to F, all in CAPITAL LETTERS')

        texto_user = input()
        print('-' * 30)

        if(escolha_user == opcao1):
          condicao_decimal = verificar_decimal(texto_user)
          if(condicao_decimal == True):
            resultado1, resultado2 = decimal_para_demais(texto_user)
            print(f'Decimal -> Hexadecimal = {resultado1}')
            print(f'Decimal -> Binary = {resultado2}')
            break
          else:
            print("Error! You didn't typed just numbers!")
        elif(escolha_user == opcao2):
          condicao_nibble = verificar_nibble(texto_user)
          if(condicao_nibble == True):
            resultado1, resultado2 = nibble_para_demais(texto_user)
            print(f'Binary -> Decimal = {resultado1}')
            print(f'Binary -> Hexadecimal = {resultado2}')
            break
          else:
            print("Error! You didn't typed just the numbers 0 and 1!")
        else:
          condicao_hexadecimal = verificar_hexadecimal(texto_user)
          if(condicao_hexadecimal == True):
            resultado1, resultado2 = hexadecimal_para_demais(texto_user)
            print(f'Hexadecimal -> Decimal = {resultado1}')
            print(f'Hexadecimal -> Binary = {resultado2}')
            break
          else:
            print("Error! You didn't typed just numbers and the available letters")
        print('Please, try again!')
        print('-' * 30)
      break
    else:
      print("Error! You didn't type any of the available options!")
      print('Please, try again!')
      print('-' * 30)